"""
execution_plan.py

Represents the complete execution plan generated by the LLM.

A plan may contain one or many independent tasks which are
executed sequentially by the AssistantEngine.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.models.planned_task import PlannedTask


@dataclass(slots=True, frozen=True)
class ExecutionPlan:
    """
    Ordered list of executable tasks.
    """

    summary_response: str

    tasks: tuple[PlannedTask, ...]

    @property
    def task_count(self) -> int:
        return len(self.tasks)

    @property
    def is_multi_task(self) -> bool:
        return self.task_count > 1