"""
planned_task.py

Represents a single atomic task within a larger execution plan.

Each task wraps one Intent generated by the LLM together with
its initial success response.

The dispatcher executes tasks independently.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.models.intent import Intent


@dataclass(slots=True, frozen=True)
class PlannedTask:
    """
    One executable task.
    """

    task_id: int

    intent: Intent

    response: str